const totalCounts = {
  '(not set)': 55,
  About: 359,
  Babel: 11,
  Blog: 225,
  Contact: 33,
  HR转型研发那些事儿: 27,
  'Personal Development for Smart People': 21,
  'Personal Development for Smart People —— Afterword': 20,
  'Personal Development for Smart People —— Chapter1 Truth': 146,
  'Personal Development for Smart People —— Chapter10 Money': 32,
  'Personal Development for Smart People —— Chapter11 Health': 9,
  'Personal Development for Smart People —— Chapter12 RelationShips': 16,
  'Personal Development for Smart People —— Chapter13 Spirituality': 11,
  'Personal Development for Smart People —— Chapter2 Love': 57,
  'Personal Development for Smart People —— Chapter3 Power': 43,
  'Personal Development for Smart People —— Chapter4 Oneness': 24000,
  'Personal Development for Smart People —— Chapter5 Authority': 15,
  'Personal Development for Smart People —— Chapter6 Courage': 23,
  'Personal Development for Smart People —— Chapter7 Intelligence': 33,
  'Personal Development for Smart People —— Chapter8 Habits': 24,
  'Personal Development for Smart People —— Chapter9 Career': 37,
  'Personal Development for Smart People —— Introduction': 112,
  'Personal Development for Smart People —— 引言': 3,
  Tags: 119,
  javascript: 10,
  人生: 14,
  '代码质量好一点，同事爱你多一点😚': 6,
  关于: 218,
  '分类？分形？不知怎么描述': 4,
  '初创公司HR如何快速招聘研发精英(长图)': 17,
  '别再纠结“性能优化方案有哪些”了': 62,
  前端: 18,
  '前端性能优化-话题终结者': 10,
  '开张咯😇': 50,
  未归类: 19,
  标签: 73,
  策论: 3,
  '网页性能优化-meta': 17,
  联系: 27,
  '计算机网络基础(0门槛)': 114,
  追谏: 298,
  通识: 15,
  '青年在选择职业时的考虑(长图)': 16,
  青年选择职业时的考虑: 12,
};
module.exports = totalCounts;
