name: 'Update Google Analytics Data'
on:
  # 先留着，CI 挂了调试还是用得到的
  # push:
  #   branches:
  #     - github-action/test-flow
  schedule:
    - cron: '0 21 * * *'
jobs:
  update-analytics-data:
    runs-on: ubuntu-latest
    env:
      # 老UA使用(再启用，UA的账号好像有问题)
      client_email: ${{secrets.GA_AUTH_CLIENT_EMAIL}}
      private_key: ${{secrets.GA_AUTH_PRIVATE_KEY}}

      # 新GA4(使用中)
      ga4_client_email: ${{secrets.GA4_AUTH_CLIENT_EMAIL}}
      ga4_private_key: ${{secrets.GA4_AUTH_PRIVATE_KEY}}
      github_token: ${{secrets.GH_ACTION_DEPLOY_KEY}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18.17.0
      # 获取UA数据(已封存)
      # - run: npm install googleapis moment
      # - run: node bin/setAnalyticsData.js

      # 获取GA数据(使用中)
      - run: rm package-lock.json yarn.lock
      # 不用 legacy 不行，还是早点升级吧
      - run: npm install @google-analytics/data moment --legacy-peer-deps
      - run: node bin/ga4/setAnalyticsData.js
      # 更新博客数据
      - run: node bin/updateContent.js
      # 合入master并发布
      - run: npm run install-action
      - run: node bin/commitToMaster.js
